### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/eventgrid-emulator#1]
Hello!

We would like to know how is the emulator going... Is it somehow usable? If yes, how to can run it, create topics and register the subscribers?

Thanks!

**Comment by marstr** [comment]
Hey @galvesribeiro, thanks for your interest! This is definitely currently in preview/development. I expect to start working on this again in the next week or so.

In terms of usage, I'd like to just have this process spin up a local webserver that has endpoints matching the respective ARM and Event Grid Topic ones. That way interacting with it should be as simple as swapping out the root of the URL.

**Comment by galvesribeiro** [comment]
Hello @marstr, thanks for getting back.

I've played and created one using Orleans and Asp.Net Core that works. I would just change the URLs to match more the ARM ones. https://github.com/galvesribeiro/EventGridEmulator

The plan was to have it published as a docker container so it would be simple to spin of an instance.

In case you are getting back to work on it, I would rather have the official emulators then 😄

**Comment by marstr** [comment]
Sounds good! I like the idea of publishing this as a Docker image as well.

**Comment by SimonLuckenuik** [comment]
@marstr very happy to see something official being developed.

I was currently using that one: https://github.com/ravinsp/eventgrid-emulator
Not maintained anymore apparently, but does the trick for simple HTTP publications, simpler than an ngrok setup with the actual Event Grid endpoint running in the cloud.

I also tried playing with the event grid relay listener (https://github.com/Azure-Samples/event-grid-relay-listener), but in the end it was not convenient to have the actual event grid endpoint in the cloud and have all developers manage their own cloud resource.

Do you have a roadmap? Is @djrosanova in the loop? :-)

**Comment by tomkerkhove** [comment]
Is there an update on this? Looking forward to this.

**Comment by pm7y** [comment]
I recently created this for my own purposes which might be of use to you https://github.com/pmcilreavy/AzureEventGridSimulator

**Comment by adetayorabiu** [comment]
Any hope this (official emulator) is getting completed any time soon?
